import { readFileSync } from 'fs';
import type { Screenshot } from './screenshotter.js';

/**
 * Posts a PR comment with embedded screenshots.
 *
 * GitHub doesn't support base64 images in Markdown comments directly,
 * so we upload each screenshot as a repository file asset via the
 * Contents API (to a temp branch) then reference the raw URL.
 * In GitHub Actions the simpler approach is to upload as artifacts and
 * link them — but artifacts expire. For permanent links we use the
 * workflow run's artifact download approach OR the simplest approach
 * that actually works in PRs: paste images as base64 in a <details> block.
 *
 * This reporter uses the GitHub issue comment API. Images are uploaded
 * to a dedicated screenshots branch so they get a permanent raw URL.
 */

interface GithubReporterOptions {
  owner: string;
  repo: string;
  prNumber: number;
  screenshots: Screenshot[];
  runUrl?: string;
}

async function githubFetch(path: string, options: RequestInit = {}) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error('GITHUB_TOKEN is required');

  const res = await fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      ...(options.headers ?? {}),
    },
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`GitHub API ${res.status} on ${path}: ${body}`);
  }

  return res.json();
}

async function ensureBranch(owner: string, repo: string, branch: string) {
  try {
    await githubFetch(`/repos/${owner}/${repo}/git/ref/heads/${branch}`);
    // Branch exists
  } catch {
    // Create from HEAD of default branch
    const defaultRef = await githubFetch(`/repos/${owner}/${repo}/git/ref/heads/main`).catch(
      () => githubFetch(`/repos/${owner}/${repo}/git/ref/heads/master`),
    );
    await githubFetch(`/repos/${owner}/${repo}/git/refs`, {
      method: 'POST',
      body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: (defaultRef as any).object.sha }),
    });
    console.log(`[reporter] Created branch ${branch}`);
  }
}

async function uploadScreenshot(
  owner: string,
  repo: string,
  branch: string,
  prNumber: number,
  screenshot: Screenshot,
): Promise<string> {
  const content = readFileSync(screenshot.path);
  const base64 = content.toString('base64');
  const fileName = `${screenshot.route.replace(/\//g, '_').replace(/^_/, '') || 'home'}.png`;
  const path = `pr-${prNumber}/${fileName}`;

  // Check if file already exists (need its SHA to update)
  let sha: string | undefined;
  try {
    const existing = (await githubFetch(
      `/repos/${owner}/${repo}/contents/${path}?ref=${branch}`,
    )) as any;
    sha = existing.sha;
  } catch {
    // File doesn't exist yet — that's fine
  }

  await githubFetch(`/repos/${owner}/${repo}/contents/${path}`, {
    method: 'PUT',
    body: JSON.stringify({
      message: `chore: ui-check screenshot for ${screenshot.route} (PR #${prNumber})`,
      content: base64,
      branch,
      ...(sha ? { sha } : {}),
    }),
  });

  const rawUrl = `https://raw.githubusercontent.com/${owner}/${repo}/${branch}/${path}`;
  console.log(`[reporter] Uploaded ${fileName} → ${rawUrl}`);
  return rawUrl;
}

export async function postPrComment(options: GithubReporterOptions): Promise<void> {
  const { owner, repo, prNumber, screenshots, runUrl } = options;

  const screenshotsBranch = 'ui-check-screenshots';

  console.log('\n[reporter] Uploading screenshots to GitHub...');
  await ensureBranch(owner, repo, screenshotsBranch);

  const uploadedImages: { screenshot: Screenshot; url: string }[] = [];
  for (const s of screenshots) {
    const url = await uploadScreenshot(owner, repo, screenshotsBranch, prNumber, s);
    uploadedImages.push({ screenshot: s, url });
  }

  const timestamp = new Date().toUTCString();
  const sections = uploadedImages
    .map(
      ({ screenshot, url }) => `
### \`${screenshot.route}\` — ${screenshot.label}

**Triggered by:** ${screenshot.triggeredBy.map((f) => `\`${f}\``).join(', ')}

![${screenshot.route} screenshot](${url})
`,
    )
    .join('\n---\n');

  const body = `## UI Check Results

> Automatically generated by the UI Check bot · ${timestamp}${runUrl ? `\n> [View workflow run](${runUrl})` : ''}

**${screenshots.length} route(s) affected and screenshotted.**

${sections}

<sub>Screenshots are stored on the \`${screenshotsBranch}\` branch and updated on each run.</sub>
`;

  await githubFetch(`/repos/${owner}/${repo}/issues/${prNumber}/comments`, {
    method: 'POST',
    body: JSON.stringify({ body }),
  });

  console.log(`\n[reporter] Comment posted on PR #${prNumber}`);
}
